#!/usr/bin/python


## install libaries

try:
    import pandas as pd
    from argument import Argument
    from database import Connection
except ModuleNotFoundError:
    from tools import InstallPackages
    InstallPackages({'pandas', 'argparse', 'pyodbc'})
    import pandas as pd
    from argument import Argument
    from database import Connection



## read file
import sys

print('Number of arguments:', len(sys.argv), 'arguments.')
print('Argument List:', str(sys.argv))
